### ISSUE TITLE
[FEAT] 게시물 - 사진

### ISSUE THREAD

**Issue by boriiiborii** [dormitoryFamilies/iOS#16]
## ID 🪪
| 칸반 ID | iOS &nbsp; |
|:-------:|:-------:|

<br/>

##  TODO 📝
- [x] 사진 GET요청
- [x] 사진 추가 UI (stack으로 구현)
- [ ] 사진 추가 로직
- [ ] 사진 삭제 로직

**Comment by boriiiborii** [comment]
이슈 다시 만들 예정
