### ISSUE TITLE
[DESIGN] 긱사생활 설정 / 수면패턴 레이아웃

### ISSUE THREAD

**Issue by nss321** [dormitoryFamilies/iOS#19]
## ID 🪪
| 칸반 ID | iOS 7 |
|:-------:|:-------:|

<br/>

##  TODO 📝
- [x] 이미지 에셋 추가(폴더링)
- [x] navigation back button item 정상 적용 확인
- [x] navigation custom 작업 -> 코드 스니펫 또는 미리 정의해두면 편하지 않을지? (제목만 parameter로 넘겨주는 방식으로)
- [x] 화면 전체 레이아웃 작업
