### ISSUE TITLE
[FIX, ADD] 게시판 목록, 디테일 못한 구현 및 버그 해결

### ISSUE THREAD

**Issue by boriiiborii** [dormitoryFamilies/iOS#35]
## ID 🪪
| 칸반 ID | iOS &nbsp; |
|:-------:|:-------:|

<br/>

##  TODO 📝
- [ ] 대댓글 날짜 포멧 변경
- [ ] 대댓글 시간 재세팅
- [ ] 댓글/대댓글 isWriter일시 더보기버튼 띄우고 아닐시 UI가리기
- [ ] 초기 기숙사를 본관으로 지정
- [ ] status변경시 모집완료와 모집중 toggle기능

**Comment by boriiiborii** [comment]
이슈 다시 만들 예정
