### ISSUE TITLE
룸메 매칭 수정사항 반영

### ISSUE THREAD

**Issue by nss321** [dormitoryFamilies/iOS#89]
## ID 🪪
| 칸반 ID | iOS 18 |
|:-------:|:-------:|

<br/>

##  TODO 📝
- [x]  MBTI 뷰 수정 - 아예 선택 X or 모두 선택시 다음 버튼 활성화
- [x]  셀 선택시 UI 변경
- [x]  도움말 버튼 클릭시 얼럿
- [x]  팔수로 받는 데이터 다시 확인
- [x]  탭바 비활성화
